/**
 * Blog generator — assembles all post modules into src/data/blog.js
 * and writes one SVG cover per post into public/blog/.
 *
 * Run: node scripts/generate-blog.mjs
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { slugify, makePost, hash, CATEGORY_META } from "./blog/lib.mjs";
import { coverSvg } from "./blog/covers.mjs";
import { generatePlatformPosts } from "./blog/platforms.mjs";
import { generateConverterPosts } from "./blog/converters.mjs";
import { generateCorePosts } from "./blog/core.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// 1. Collect raw posts from all modules
const rawPosts = [
  ...generatePlatformPosts(),
  ...generateConverterPosts(),
  ...generateCorePosts(),
];

// 2. Normalize slugs (core/converters use slugP or plain titles)
for (const p of rawPosts) {
  if (!p.slug) p.slug = p.slugP ? slugify(p.slugP) : slugify(p.title);
}

// 3. Deduplicate slugs (append suffix on collision)
const seen = new Map();
for (const p of rawPosts) {
  if (seen.has(p.slug)) {
    const n = seen.get(p.slug) + 1;
    seen.set(p.slug, n);
    p.slug = `${p.slug}-${n}`;
  } else {
    seen.set(p.slug, 1);
  }
}

// 4. Sort newest-first by nothing yet — dates are assigned in order,
//    so interleave modules for a natural mix: sort by slug hash for
//    deterministic pseudo-random order, then date desc falls out.
rawPosts.sort((a, b) => hash(a.slug) - hash(b.slug));

// 5. Finalize
const posts = rawPosts
  .map((p, i) => makePost(p, i, rawPosts.length))
  .sort((a, b) => b.date.localeCompare(a.date)); // newest first

// 6. Write covers
const coverDir = join(root, "public", "blog");
mkdirSync(coverDir, { recursive: true });
let written = 0;
for (const p of posts) {
  const svg = coverSvg({
    slug: p.slug,
    title: p.title,
    category: p.category,
    hashNum: hash(p.slug),
  });
  writeFileSync(join(coverDir, `${p.slug}.svg`), svg);
  written++;
}

// 7. Write src/data/blog.js
const categories = Object.keys(CATEGORY_META);
const tagIndex = {};
for (const p of posts) {
  for (const t of p.tags || []) {
    (tagIndex[t] ||= []).push(p.slug);
  }
}

const dataFile = `/**
 * AUTO-GENERATED by scripts/generate-blog.mjs — do not edit by hand.
 * ${posts.length} posts across ${categories.length} categories.
 */
export const blogCategories = ${JSON.stringify(
  Object.entries(CATEGORY_META).map(([id, meta]) => ({
    id,
    label: meta.label,
    count: posts.filter((p) => p.category === id).length,
  })),
  null,
  2
)};

export const blogPosts = ${JSON.stringify(posts, null, 2)};

export function getPostBySlug(slug) {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(post, count = 3) {
  if (!post) return [];
  return blogPosts
    .filter((p) => p.slug !== post.slug)
    .map((p) => {
      let score = p.category === post.category ? 2 : 0;
      for (const t of p.tags || []) if (post.tags?.includes(t)) score += 1;
      return { p, score };
    })
    .sort((a, b) => b.score - a.score || b.p.date.localeCompare(a.p.date))
    .slice(0, count)
    .map((x) => x.p);
}
`;

writeFileSync(join(root, "src", "data", "blog.js"), dataFile);

// 7b. Lightweight "latest posts" file for the homepage — avoids pulling
//     the full dataset into the main bundle.
const latestFile = `/**
 * AUTO-GENERATED by scripts/generate-blog.mjs — do not edit by hand.
 */
export const latestBlogPosts = ${JSON.stringify(
  posts.slice(0, 3).map(({ slug, title, description, category, cover, date, readMinutes }) => ({
    slug,
    title,
    description,
    category,
    cover,
    date,
    readMinutes,
  })),
  null,
  2
)};

export const blogPostCount = ${posts.length};
`;
writeFileSync(join(root, "src", "data", "blog-latest.js"), latestFile);

// 8. Summary
const byCat = {};
for (const p of posts) byCat[p.category] = (byCat[p.category] || 0) + 1;
console.log(`blog: generated ${posts.length} posts, ${written} covers`);
for (const [cat, n] of Object.entries(byCat)) {
  console.log(`  ${CATALOG(cat)}: ${n}`);
}
function CATALOG(id) {
  return CATEGORY_META[id]?.label || id;
}
